FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    curl \
    gnupg \
    lsb-release \
    apt-transport-https && \
    add-apt-repository ppa:ondrej/php -y && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    php5.6-fpm \
    php5.6-zip \
    php5.6-mysql \
    php5.6-curl \
    php5.6-mbstring \
    php5.6-json \
    php5.6-pdo \
    php5.6-xml && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

